version: '3'

services:
  app:
    build: .docker/app
    working_dir: /var/www/src
    ports:
      - target: ${VITE_PORT:-5173}
        published: ${VITE_PORT:-5173}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
      # 以下は頻繁に変更する時以外はコメントアウトでも問題なし(コンテナが最新である前提)
      - type: bind
        source: .docker/app/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: .docker/app/www.conf
        target: /usr/local/etc/php-fpm.d/www.conf
      - type: bind
        source: .docker/app/xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - VITE_HOST=localhost:${WEB_PUBLISHED_PORT:-8080}
      - VITE_PORT=${VITE_PORT:-5173}

  nginx:
    build: .docker/nginx
    networks:
      # - local-network
      - default
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-8080}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /var/www/src
      - type: bind
        source: .docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

  mysql:
    build: .docker/mysql
    ports:
      - target: 3306
        published: ${DB_PUBLISHED_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpw}
      MYSQL_DATABASE: ${DB_DATABASE:-local_db}
      MYSQL_USER: ${DB_USERNAME:-dbuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbuserpw}

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - target: 8080
  #       published: ${SWAGGER_PUBLISHED_PORT:-8081}
  #       protocol: tcp
  #       mode: host
  #   volumes:
  #     - type: bind
  #       source: ./src
  #       target: /tmp
  #   environment:
  #     - SWAGGER_JSON=/tmp/openapi.yaml
  
  # mailpit:
  #   image: axllent/mailpit
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  #   environment:
  #     MP_DATA_FILE: /home/mailpit/mails
  #     # MP_SMTP_SSL_CERT: /keys/cert.pem
  #     # MP_SMTP_SSL_KEY: /keys/privkey.pem
  #   volumes:
  #     - type: volume
  #       source: mail-store
  #       target: /home/mailpit/mails

volumes:
  db-store:
  # mail-store:

# networks:
#   local-network:
#     external: true